export * from "./admin.system.config.controller";
export * from "./admin.system.dept.controller";
export * from "./admin.system.dict-item.controller";
export * from "./admin.system.dict.controller";
export * from "./admin.system.menu.controller";
export * from "./admin.system.monitor.login-log.controller";
export * from "./admin.system.monitor.serve.controller";
export * from "./admin.system.role.controller";
export * from "./admin.system.user.controller";
