export const ACTION_CREATE_BLOG_CATEGORY = "ACTION_CREATE_BLOG_CATEGORY";
export const ACTION_UPDATE_BLOG_CATEGORY = "ACTION_UPDATE_BLOG_CATEGORY";
export const ACTION_DELETE_BLOG_CATEGORY = "ACTION_DELETE_BLOG_CATEGORY";
