export type MenuSeed = {
  key: string;
  parentKey?: string | null;
  name: string;
  type: number;
  path?: string | null;
  pathFile?: string | null;
  permission?: string | null;
  icon?: string | null;
  status?: number;
  isShow?: number;
  isCache?: number;
  isLink?: number;
  orderNo?: number;
  description?: string | null;
  remark?: string | null;
};

export const menuSeeds: MenuSeed[] = [
  {
    key: "dashboard",
    name: "Dashboard",
    type: 2,
    path: "/dashboard",
    pathFile: "admin/dashboard",
    permission: "dashboard:read",
    icon: "DashboardOutlined",
    orderNo: 1,
    isShow: 1,
  },
  {
    key: "ai",
    name: "AI",
    type: 1,
    path: "/ai",
    icon: "RobotOutlined",
    orderNo: 2,
    isShow: 1,
  },
  {
    key: "ai-chatbot",
    parentKey: "ai",
    name: "Chatbot",
    type: 2,
    path: "/ai/chatbot",
    pathFile: "admin/ai/chatbot",
    permission: "system:ai:simplechat:read",
    icon: "MessageOutlined",
    orderNo: 1,
    isShow: 1,
  },
  {
    key: "news",
    name: "News",
    type: 1,
    path: "/news",
    icon: "NotificationOutlined",
    orderNo: 3,
    isShow: 1,
  },
  {
    key: "news-list",
    parentKey: "news",
    name: "List",
    type: 2,
    path: "/news/list",
    pathFile: "admin/news/list",
    permission: "news:list:read",
    icon: "UnorderedListOutlined",
    orderNo: 1,
    isShow: 1,
  },
  {
    key: "news-edit",
    parentKey: "news",
    name: "Edit",
    type: 2,
    path: "/news/edit",
    pathFile: "admin/news/edit",
    /** Same gate as list/create API (`news:list:read`). */
    permission: "news:list:read",
    icon: "FormOutlined",
    orderNo: 2,
    isShow: 1,
  },
  {
    key: "blog",
    name: "博客",
    type: 1,
    path: "/blog",
    icon: "EditOutlined",
    orderNo: 4,
    isShow: 1,
  },
  {
    key: "blog-list",
    parentKey: "blog",
    name: "列表",
    type: 2,
    path: "/blog/list",
    pathFile: "admin/blog/list",
    permission: "blog:list:read",
    icon: "UnorderedListOutlined",
    orderNo: 1,
    isShow: 1,
  },
  {
    key: "blog-edit",
    parentKey: "blog",
    name: "新建文章",
    type: 2,
    path: "/blog/edit",
    /** 与路由 `routes/admin/blog/create.tsx`（URL `/blog/edit`）一致，便于侧栏与权限对齐 */
    pathFile: "admin/blog/create",
    /** Same gate as list/create API (`blog:list:read`). */
    permission: "blog:list:read",
    icon: "FormOutlined",
    orderNo: 2,
    isShow: 1,
  },
  {
    key: "blog-edit-article",
    parentKey: "blog",
    name: "编辑",
    type: 2,
    path: "/blog/edit/:id",
    pathFile: "admin/blog/edit",
    permission: "blog:list:read",
    icon: "EditOutlined",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "blog-detail",
    parentKey: "blog",
    name: "Detail",
    type: 2,
    path: "/blog/detail",
    pathFile: "admin/blog/detail",
    permission: "blog:detail:read",
    icon: "FileTextOutlined",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "profile",
    name: "Profile",
    type: 1,
    path: "/profile",
    icon: "UserOutlined",
    orderNo: 5,
    isShow: 1,
  },
  {
    key: "profile-home",
    parentKey: "profile",
    name: "Account",
    type: 2,
    path: "/profile/account",
    pathFile: "admin/profile/account",
    permission: "profile:account:read",
    icon: "HomeOutlined",
    orderNo: 1,
    isShow: 1,
  },
  {
    key: "profile-link",
    parentKey: "profile",
    name: "Link",
    type: 2,
    path: "/profile/link",
    pathFile: "admin/profile/link/category",
    permission: "profile:link:read",
    icon: "LinkOutlined",
    orderNo: 2,
    isShow: 1,
  },
  {
    key: "tools",
    name: "Tools",
    type: 1,
    path: "/tools",
    icon: "ToolOutlined",
    orderNo: 6,
    isShow: 1,
  },
  {
    key: "tools-mail",
    parentKey: "tools",
    name: "Mail",
    type: 2,
    path: "/tools/mail",
    pathFile: "admin/tools/mail",
    permission: "tools:mail:read",
    icon: "MailOutlined",
    orderNo: 1,
    isShow: 1,
  },
  {
    key: "tools-storage",
    parentKey: "tools",
    name: "Storage",
    type: 2,
    path: "/tools/storage",
    pathFile: "admin/tools/storage",
    permission: "tools:storage:read",
    icon: "DatabaseOutlined",
    orderNo: 2,
    isShow: 1,
  },
  {
    key: "about",
    name: "About",
    type: 2,
    path: "/about",
    pathFile: "admin/about",
    permission: "about:read",
    icon: "InfoCircleOutlined",
    orderNo: 8,
    isShow: 1,
  },
  {
    key: "system",
    name: "System",
    type: 1,
    path: "/system",
    icon: "SettingOutlined",
    orderNo: 7,
    isShow: 1,
  },
  {
    key: "system-user",
    parentKey: "system",
    name: "User",
    type: 2,
    path: "/system/user",
    pathFile: "admin/system/user",
    permission: "system:user:read",
    icon: "TeamOutlined",
    orderNo: 1,
    isShow: 1,
  },
  {
    key: "system-role",
    parentKey: "system",
    name: "Role",
    type: 2,
    path: "/system/role",
    pathFile: "admin/system/role",
    permission: "system:role:read",
    icon: "UserSwitchOutlined",
    orderNo: 2,
    isShow: 1,
  },
  {
    key: "system-menu",
    parentKey: "system",
    name: "Menu",
    type: 2,
    path: "/system/menu",
    pathFile: "admin/system/menu",
    permission: "system:menu:read",
    icon: "MenuOutlined",
    orderNo: 3,
    isShow: 1,
  },
  {
    key: "system-dept",
    parentKey: "system",
    name: "Department",
    type: 2,
    path: "/system/dept",
    pathFile: "admin/system/dept",
    permission: "system:dept:read",
    icon: "ApartmentOutlined",
    orderNo: 4,
    isShow: 1,
  },
  {
    key: "system-dict",
    parentKey: "system",
    name: "Dictionary",
    type: 2,
    path: "/system/dict",
    pathFile: "admin/system/dict",
    permission: "system:dict:read",
    icon: "BookOutlined",
    orderNo: 5,
    isShow: 1,
  },
  {
    key: "system-config",
    parentKey: "system",
    name: "Config",
    type: 2,
    path: "/system/config",
    pathFile: "admin/system/config",
    permission: "system:config:read",
    icon: "ControlOutlined",
    orderNo: 6,
    isShow: 1,
  },
  {
    key: "system-monitor",
    parentKey: "system",
    name: "Monitor",
    type: 1,
    path: "/system/monitor",
    icon: "MonitorOutlined",
    orderNo: 7,
    isShow: 1,
  },
  {
    key: "system-monitor-loginlog",
    parentKey: "system-monitor",
    name: "Login Log",
    type: 2,
    path: "/system/monitor/loginlog",
    pathFile: "admin/system/monitor/loginlog",
    permission: "system:monitor:loginlog:read",
    icon: "LoginOutlined",
    orderNo: 1,
    isShow: 1,
  },
  {
    key: "system-monitor-operate",
    parentKey: "system-monitor",
    name: "Operate",
    type: 2,
    path: "/system/monitor/operate",
    pathFile: "admin/system/monitor/operate",
    permission: "system:monitor:operate:read",
    icon: "ToolOutlined",
    orderNo: 2,
    isShow: 1,
  },
  {
    key: "system-monitor-serve",
    parentKey: "system-monitor",
    name: "Serve",
    type: 2,
    path: "/system/monitor/serve",
    pathFile: "admin/system/monitor/serve",
    permission: "system:monitor:serve:read",
    icon: "CloudServerOutlined",
    orderNo: 3,
    isShow: 1,
  },
  {
    key: "perm-system-user-read",
    parentKey: "system-user",
    name: "Read",
    type: 3,
    permission: "system:user:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-system-user-create",
    parentKey: "system-user",
    name: "Create",
    type: 3,
    permission: "system:user:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-system-user-update",
    parentKey: "system-user",
    name: "Update",
    type: 3,
    permission: "system:user:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-system-user-delete",
    parentKey: "system-user",
    name: "Delete",
    type: 3,
    permission: "system:user:delete",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "perm-system-role-read",
    parentKey: "system-role",
    name: "Read",
    type: 3,
    permission: "system:role:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-system-role-create",
    parentKey: "system-role",
    name: "Create",
    type: 3,
    permission: "system:role:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-system-role-update",
    parentKey: "system-role",
    name: "Update",
    type: 3,
    permission: "system:role:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-system-role-delete",
    parentKey: "system-role",
    name: "Delete",
    type: 3,
    permission: "system:role:delete",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "perm-system-menu-read",
    parentKey: "system-menu",
    name: "Read",
    type: 3,
    permission: "system:menu:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-system-menu-create",
    parentKey: "system-menu",
    name: "Create",
    type: 3,
    permission: "system:menu:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-system-menu-update",
    parentKey: "system-menu",
    name: "Update",
    type: 3,
    permission: "system:menu:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-system-menu-delete",
    parentKey: "system-menu",
    name: "Delete",
    type: 3,
    permission: "system:menu:delete",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "perm-system-dept-read",
    parentKey: "system-dept",
    name: "Read",
    type: 3,
    permission: "system:dept:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-system-dept-create",
    parentKey: "system-dept",
    name: "Create",
    type: 3,
    permission: "system:dept:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-system-dept-update",
    parentKey: "system-dept",
    name: "Update",
    type: 3,
    permission: "system:dept:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-system-dept-delete",
    parentKey: "system-dept",
    name: "Delete",
    type: 3,
    permission: "system:dept:delete",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "perm-system-dict-read",
    parentKey: "system-dict",
    name: "Read",
    type: 3,
    permission: "system:dict:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-system-dict-create",
    parentKey: "system-dict",
    name: "Create",
    type: 3,
    permission: "system:dict:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-system-dict-update",
    parentKey: "system-dict",
    name: "Update",
    type: 3,
    permission: "system:dict:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-system-dict-delete",
    parentKey: "system-dict",
    name: "Delete",
    type: 3,
    permission: "system:dict:delete",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "perm-system-config-read",
    parentKey: "system-config",
    name: "Read",
    type: 3,
    permission: "system:config:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-system-config-create",
    parentKey: "system-config",
    name: "Create",
    type: 3,
    permission: "system:config:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-system-config-update",
    parentKey: "system-config",
    name: "Update",
    type: 3,
    permission: "system:config:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-system-config-delete",
    parentKey: "system-config",
    name: "Delete",
    type: 3,
    permission: "system:config:delete",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-loginlog-read",
    parentKey: "system-monitor-loginlog",
    name: "Login Log Read",
    type: 3,
    permission: "system:monitor:loginlog:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-loginlog-create",
    parentKey: "system-monitor-loginlog",
    name: "Login Log Create",
    type: 3,
    permission: "system:monitor:loginlog:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-loginlog-update",
    parentKey: "system-monitor-loginlog",
    name: "Login Log Update",
    type: 3,
    permission: "system:monitor:loginlog:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-loginlog-delete",
    parentKey: "system-monitor-loginlog",
    name: "Login Log Delete",
    type: 3,
    permission: "system:monitor:loginlog:delete",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-serve-read",
    parentKey: "system-monitor-serve",
    name: "Serve Read",
    type: 3,
    permission: "system:monitor:serve:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-serve-create",
    parentKey: "system-monitor-serve",
    name: "Serve Create",
    type: 3,
    permission: "system:monitor:serve:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-serve-update",
    parentKey: "system-monitor-serve",
    name: "Serve Update",
    type: 3,
    permission: "system:monitor:serve:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-serve-delete",
    parentKey: "system-monitor-serve",
    name: "Serve Delete",
    type: 3,
    permission: "system:monitor:serve:delete",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-operate-read",
    parentKey: "system-monitor-operate",
    name: "Operate Read",
    type: 3,
    permission: "system:monitor:operate:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-operate-create",
    parentKey: "system-monitor-operate",
    name: "Operate Create",
    type: 3,
    permission: "system:monitor:operate:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-operate-update",
    parentKey: "system-monitor-operate",
    name: "Operate Update",
    type: 3,
    permission: "system:monitor:operate:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-operate-delete",
    parentKey: "system-monitor-operate",
    name: "Operate Delete",
    type: 3,
    permission: "system:monitor:operate:delete",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "perm-tools-mail-read",
    parentKey: "tools-mail",
    name: "Mail Read",
    type: 3,
    permission: "tools:mail:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-tools-mail-create",
    parentKey: "tools-mail",
    name: "Mail Create",
    type: 3,
    permission: "tools:mail:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-tools-mail-update",
    parentKey: "tools-mail",
    name: "Mail Update",
    type: 3,
    permission: "tools:mail:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-tools-mail-delete",
    parentKey: "tools-mail",
    name: "Mail Delete",
    type: 3,
    permission: "tools:mail:delete",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "perm-tools-storage-read",
    parentKey: "tools-storage",
    name: "Storage Read",
    type: 3,
    permission: "tools:storage:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-tools-storage-create",
    parentKey: "tools-storage",
    name: "Storage Create",
    type: 3,
    permission: "tools:storage:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-tools-storage-update",
    parentKey: "tools-storage",
    name: "Storage Update",
    type: 3,
    permission: "tools:storage:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-tools-storage-delete",
    parentKey: "tools-storage",
    name: "Storage Delete",
    type: 3,
    permission: "tools:storage:delete",
    orderNo: 4,
    isShow: 0,
  },
];
