/**
 * Generates `seed.sql` from `menuSeeds` + role roots (single source of truth in TS).
 * Run: pnpm -F @workspace/seed run generate:seed-sql
 *
 * Idempotent: clears previous seeded rows (`m-*` legacy ids + any seed UUIDs)
 * then re-inserts three fixed roles (user / admin / superadmin), all menus,
 * and `sys_menu_role`. Does not create auth users — assign roles in the admin
 * UI or via sign-up defaults.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";

import { menuSeeds, type MenuSeed } from "../menus/index.js";
import { ADMIN_MENU_ROOT_KEYS, USER_MENU_ROOT_KEYS } from "../menus/role-menu-roots.js";
import { LOCAL_ROLE_IDS } from "./role-ids.js";

const OUT = path.join(import.meta.dirname, "seed.sql");

/** Prefix range used by seed UUIDs. Kept disjoint from auth / app-generated ids. */
const MENU_SEED_PREFIX = "01900010-0000-7000-8000-";
const MENU_SEED_TOTAL = 1024; // 12-hex tail → 000..(TOTAL-1)

function menuSeedId(index: number): string {
  if (index < 0 || index >= MENU_SEED_TOTAL) {
    throw new Error(
      `[generate-rbac-sql] menuSeedId overflow: index ${index} (max ${MENU_SEED_TOTAL - 1})`,
    );
  }
  return `${MENU_SEED_PREFIX}${index.toString(16).padStart(12, "0")}`;
}

function sortMenusForInsert(seeds: MenuSeed[]): MenuSeed[] {
  const out: MenuSeed[] = [];
  const remaining = [...seeds];
  while (remaining.length) {
    const idx = remaining.findIndex((s) => !s.parentKey || out.some((o) => o.key === s.parentKey));
    if (idx === -1) throw new Error("[generate-rbac-sql] Invalid menu seeds");
    out.push(remaining[idx]!);
    remaining.splice(idx, 1);
  }
  return out;
}

function collectKeysFromRoots(roots: Set<string>, seeds: MenuSeed[]): Set<string> {
  const result = new Set<string>();
  const walk = (key: string) => {
    if (result.has(key)) return;
    result.add(key);
    for (const s of seeds) {
      if (s.parentKey === key) walk(s.key);
    }
  };
  for (const r of roots) walk(r);
  return result;
}

function sqlStr(s: string | null | undefined): string {
  if (s == null) return "NULL";
  return `'${String(s).replace(/'/g, "''")}'`;
}

function sqlInt(n: number | null | undefined): string {
  if (n == null) return "NULL";
  return String(n);
}

const TS = `(CAST(unixepoch('subsecond') * 1000 AS INTEGER))`;

function main() {
  const ordered = sortMenusForInsert(menuSeeds);
  if (ordered.length >= MENU_SEED_TOTAL) {
    throw new Error(
      `[generate-rbac-sql] menuSeeds (${ordered.length}) exceeds UUID capacity (${MENU_SEED_TOTAL - 1}). Bump MENU_SEED_PREFIX or split into multiple ranges.`,
    );
  }

  const keyToId = new Map<string, string>();
  ordered.forEach((seed, idx) => {
    keyToId.set(seed.key, menuSeedId(idx));
  });

  const allKeys = new Set(menuSeeds.map((s) => s.key));
  const adminKeys = collectKeysFromRoots(ADMIN_MENU_ROOT_KEYS, menuSeeds);
  const userKeys = collectKeysFromRoots(USER_MENU_ROOT_KEYS, menuSeeds);

  const lines: string[] = [
    "-- Generated by tools/seed/src/rbac/sql/generate.ts — do not edit by hand.",
    "-- Re-run: pnpm -F @workspace/seed run generate:seed-sql",
    "--",
    "-- Fixed RBAC: roles user / admin / superadmin + full menu tree + role–menu links.",
    `-- Menu ids are deterministic UUIDs prefixed ${MENU_SEED_PREFIX} (12-hex tail = 0..${ordered.length - 1}).`,
    "-- Retry-safe: removes any legacy 'm-*' rows + current seed UUIDs, then re-inserts.",
    "-- Auth users are not created here — use the app UI (or sign-up) and assign roles there.",
    "",
    "PRAGMA foreign_keys = ON;",
    "",
    "-- Reset: links first (any role), then menus",
    "DELETE FROM sys_menu_role WHERE menu_id GLOB 'm-*' OR menu_id LIKE '" +
      MENU_SEED_PREFIX +
      "%';",
    "DELETE FROM sys_menu WHERE id GLOB 'm-*' OR id LIKE '" + MENU_SEED_PREFIX + "%';",
    "",
    "-- Three application roles (fixed UUIDs; `user` = default sign-up role in rbac-login)",
    `INSERT OR REPLACE INTO sys_role (id, name, value, description, remark, status, created_at, updated_at) VALUES (`,
    `  '${LOCAL_ROLE_IDS.user}', 'User', 'user', 'Default sign-up role', NULL, 1, ${TS}, ${TS}`,
    `);`,
    `INSERT OR REPLACE INTO sys_role (id, name, value, description, remark, status, created_at, updated_at) VALUES (`,
    `  '${LOCAL_ROLE_IDS.superadmin}', 'Super Admin', 'superadmin', 'Full menu access', NULL, 1, ${TS}, ${TS}`,
    `);`,
    `INSERT OR REPLACE INTO sys_role (id, name, value, description, remark, status, created_at, updated_at) VALUES (`,
    `  '${LOCAL_ROLE_IDS.admin}', 'Admin', 'admin', 'Admin menu bundle', NULL, 1, ${TS}, ${TS}`,
    `);`,
    "",
    "-- Menus (parent before child)",
  ];

  for (const s of ordered) {
    const id = keyToId.get(s.key)!;
    const parentId = s.parentKey ? sqlStr(keyToId.get(s.parentKey)!) : "NULL";
    lines.push(
      `INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (`,
      `  ${sqlStr(id)}, ${sqlStr(s.name)}, ${s.type}, ${sqlStr(s.description)}, ${sqlStr(s.remark)}, ${sqlStr(s.icon)}, ${sqlStr(s.path)}, ${sqlStr(s.pathFile)}, ${sqlInt(s.status ?? 1)}, ${sqlInt(s.isShow ?? 1)}, ${sqlInt(s.isCache ?? 0)}, ${sqlStr(s.permission)}, ${sqlInt(s.isLink ?? 0)}, ${sqlInt(s.orderNo ?? 0)}, ${TS}, ${TS}, ${parentId}`,
      `);`,
    );
  }

  lines.push("", "-- Role–menu links");

  let mrCounter = 1;
  function nextMenuRoleId(): string {
    const n = String(mrCounter++).padStart(12, "0");
    return `01900030-0000-7000-8000-${n}`;
  }

  const pairs: { roleId: string; keys: Set<string> }[] = [
    { roleId: LOCAL_ROLE_IDS.superadmin, keys: allKeys },
    { roleId: LOCAL_ROLE_IDS.admin, keys: adminKeys },
    { roleId: LOCAL_ROLE_IDS.user, keys: userKeys },
  ];

  for (const { roleId, keys } of pairs) {
    for (const key of keys) {
      if (!allKeys.has(key)) continue;
      const menuId = keyToId.get(key);
      if (!menuId) continue;
      const id = nextMenuRoleId();
      lines.push(
        `INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (`,
        `  '${id}', '${roleId}', '${menuId}', ${TS}, ${TS}`,
        `);`,
      );
    }
  }

  lines.push("", "-- End RBAC seed");

  writeFileSync(OUT, lines.join("\n") + "\n", "utf8");
  console.log(
    `[generate-rbac-sql] Wrote ${OUT} (${ordered.length} menus, ${mrCounter - 1} menu_role rows).`,
  );
}

main();
