-- Generated by tools/seed/src/rbac/sql/generate.ts — do not edit by hand.
-- Re-run: pnpm -F @workspace/seed run generate:seed-sql
--
-- Fixed RBAC: roles user / admin / superadmin + full menu tree + role–menu links.
-- Menu ids are deterministic UUIDs prefixed 01900010-0000-7000-8000- (12-hex tail = 0..76).
-- Retry-safe: removes any legacy 'm-*' rows + current seed UUIDs, then re-inserts.
-- Auth users are not created here — use the app UI (or sign-up) and assign roles there.

PRAGMA foreign_keys = ON;

-- Reset: links first (any role), then menus
DELETE FROM sys_menu_role WHERE menu_id GLOB 'm-*' OR menu_id LIKE '01900010-0000-7000-8000-%';
DELETE FROM sys_menu WHERE id GLOB 'm-*' OR id LIKE '01900010-0000-7000-8000-%';

-- Three application roles (fixed UUIDs; `user` = default sign-up role in rbac-login)
INSERT OR REPLACE INTO sys_role (id, name, value, description, remark, status, created_at, updated_at) VALUES (
  '01900000-0000-7000-8000-000000000001', 'User', 'user', 'Default sign-up role', NULL, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT OR REPLACE INTO sys_role (id, name, value, description, remark, status, created_at, updated_at) VALUES (
  '01900000-0000-7000-8000-000000000002', 'Super Admin', 'superadmin', 'Full menu access', NULL, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT OR REPLACE INTO sys_role (id, name, value, description, remark, status, created_at, updated_at) VALUES (
  '01900000-0000-7000-8000-000000000003', 'Admin', 'admin', 'Admin menu bundle', NULL, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);

-- Menus (parent before child)
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000000', 'menu_dashboard', 2, NULL, NULL, 'DashboardOutlined', '/dashboard', 'admin/dashboard', 1, 1, 0, 'dashboard:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), NULL
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000001', 'menu_ai', 1, NULL, NULL, 'RobotOutlined', '/ai', NULL, 1, 1, 0, NULL, 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), NULL
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000002', 'menu_chatbot', 2, NULL, NULL, 'MessageOutlined', '/ai/chatbot', 'admin/ai/chatbot', 1, 1, 0, 'system:ai:chatbot:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000001'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000003', 'menu_news', 1, NULL, NULL, 'NotificationOutlined', '/news', NULL, 1, 1, 0, NULL, 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), NULL
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000004', 'menu_news_list', 2, NULL, NULL, 'UnorderedListOutlined', '/news/list', 'admin/news/list', 1, 1, 0, 'news:list:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000003'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000005', 'menu_news_edit', 2, NULL, NULL, 'FormOutlined', '/news/edit', 'admin/news/edit', 1, 1, 0, 'news:list:read', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000003'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000006', 'menu_blog', 1, NULL, NULL, 'EditOutlined', '/blog', NULL, 1, 1, 0, NULL, 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), NULL
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000007', 'menu_blog_list', 2, NULL, NULL, 'UnorderedListOutlined', '/blog/list', 'admin/blog/list', 1, 1, 0, 'blog:list:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000006'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000008', 'menu_blog_edit', 2, NULL, NULL, 'FormOutlined', '/blog/edit', 'admin/blog/create', 1, 1, 0, 'blog:list:read', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000006'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000009', 'menu_blog_edit_article', 2, NULL, NULL, 'EditOutlined', '/blog/edit/:id', 'admin/blog/edit', 1, 0, 0, 'blog:list:read', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000006'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000000a', 'menu_blog_detail', 2, NULL, NULL, 'FileTextOutlined', '/blog/detail', 'admin/blog/detail', 1, 0, 0, 'blog:detail:read', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000006'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000000b', 'menu_profile', 1, NULL, NULL, 'UserOutlined', '/profile', NULL, 1, 1, 0, NULL, 0, 5, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), NULL
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000000c', 'menu_account', 2, NULL, NULL, 'HomeOutlined', '/profile/account', 'admin/profile/account', 1, 1, 0, 'profile:account:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000000b'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000000d', 'menu_link', 2, NULL, NULL, 'LinkOutlined', '/profile/link', 'admin/profile/link/category', 1, 1, 0, 'profile:link:read', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000000b'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000000e', 'menu_tools', 1, NULL, NULL, 'ToolOutlined', '/tools', NULL, 1, 1, 0, NULL, 0, 6, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), NULL
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000000f', 'menu_mail', 2, NULL, NULL, 'MailOutlined', '/tools/mail', 'admin/tools/mail', 1, 1, 0, 'tools:mail:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000000e'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000010', 'menu_storage', 2, NULL, NULL, 'DatabaseOutlined', '/tools/storage', 'admin/tools/storage', 1, 1, 0, 'tools:storage:read', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000000e'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000011', 'menu_about', 2, NULL, NULL, 'InfoCircleOutlined', '/about', 'admin/about', 1, 1, 0, 'about:read', 0, 9, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), NULL
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000012', 'menu_system', 1, NULL, NULL, 'SettingOutlined', '/system', NULL, 1, 1, 0, NULL, 0, 7, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), NULL
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000013', 'menu_user', 2, NULL, NULL, 'TeamOutlined', '/system/user', 'admin/system/user', 1, 1, 0, 'system:user:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000012'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000014', 'menu_role', 2, NULL, NULL, 'UserSwitchOutlined', '/system/role', 'admin/system/role', 1, 1, 0, 'system:role:read', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000012'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000015', 'menu_menu', 2, NULL, NULL, 'MenuOutlined', '/system/menu', 'admin/system/menu', 1, 1, 0, 'system:menu:read', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000012'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000016', 'menu_dept', 2, NULL, NULL, 'ApartmentOutlined', '/system/dept', 'admin/system/dept', 1, 1, 0, 'system:dept:read', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000012'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000017', 'menu_dict', 2, NULL, NULL, 'BookOutlined', '/system/dict', 'admin/system/dict', 1, 1, 0, 'system:dict:read', 0, 5, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000012'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000018', 'menu_dict_item', 2, NULL, NULL, NULL, '/system/dict-item/:id', 'admin/system/dict-item', 1, 0, 0, 'system:dict:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000017'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000019', 'menu_config', 2, NULL, NULL, 'ControlOutlined', '/system/config', 'admin/system/config', 1, 1, 0, 'system:config:read', 0, 6, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000012'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000001a', 'menu_monitor', 1, NULL, NULL, 'MonitorOutlined', '/system/monitor', NULL, 1, 1, 0, NULL, 0, 7, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000012'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000001b', 'menu_login_log', 2, NULL, NULL, 'LoginOutlined', '/system/monitor/loginlog', 'admin/system/monitor/loginlog', 1, 1, 0, 'system:monitor:loginlog:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000001a'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000001c', 'menu_operate', 2, NULL, NULL, 'ToolOutlined', '/system/monitor/operate', 'admin/system/monitor/operate', 1, 1, 0, 'system:monitor:operate:read', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000001a'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000001d', 'menu_serve', 2, NULL, NULL, 'CloudServerOutlined', '/system/monitor/serve', 'admin/system/monitor/serve', 1, 1, 0, 'system:monitor:serve:read', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000001a'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000001e', 'menu_docs', 1, NULL, NULL, 'FileTextOutlined', '/docs', NULL, 1, 1, 0, NULL, 0, 8, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), NULL
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000001f', 'menu_docs_changelog', 2, NULL, NULL, 'HistoryOutlined', '/docs/changelog', 'admin/docs/changelog', 1, 1, 0, 'docs:changelog:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000001e'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000020', 'menu_docs_feedback', 2, NULL, NULL, 'MessageOutlined', '/docs/feedback', 'admin/docs/feedback', 1, 1, 0, 'docs:feedback:read', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000001e'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000021', 'Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:user:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000013'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000022', 'Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:user:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000013'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000023', 'Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:user:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000013'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000024', 'Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:user:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000013'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000025', 'Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:role:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000014'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000026', 'Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:role:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000014'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000027', 'Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:role:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000014'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000028', 'Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:role:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000014'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000029', 'Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:menu:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000015'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000002a', 'Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:menu:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000015'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000002b', 'Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:menu:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000015'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000002c', 'Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:menu:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000015'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000002d', 'Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:dept:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000016'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000002e', 'Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:dept:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000016'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000002f', 'Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:dept:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000016'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000030', 'Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:dept:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000016'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000031', 'Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:dict:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000017'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000032', 'Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:dict:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000017'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000033', 'Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:dict:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000017'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000034', 'Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:dict:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000017'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000035', 'Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:config:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000019'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000036', 'Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:config:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000019'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000037', 'Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:config:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000019'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000038', 'Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:config:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000019'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000039', 'Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:loginlog:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000001b'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000003a', 'Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:loginlog:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000001b'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000003b', 'Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:loginlog:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000001b'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000003c', 'Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:loginlog:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000001b'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000003d', 'Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:serve:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000001d'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000003e', 'Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:serve:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000001d'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000003f', 'Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:serve:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000001d'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000040', 'Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:serve:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000001d'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000041', 'Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:operate:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000001c'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000042', 'Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:operate:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000001c'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000043', 'Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:operate:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000001c'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000044', 'Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:operate:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000001c'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000045', 'Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'tools:mail:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000000f'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000046', 'Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'tools:mail:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000000f'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000047', 'Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'tools:mail:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000000f'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000048', 'Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'tools:mail:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-00000000000f'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-000000000049', 'Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'tools:storage:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000010'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000004a', 'Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'tools:storage:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000010'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000004b', 'Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'tools:storage:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000010'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  '01900010-0000-7000-8000-00000000004c', 'Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'tools:storage:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), '01900010-0000-7000-8000-000000000010'
);

-- Role–menu links
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000001', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000000', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000002', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000001', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000003', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000002', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000004', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000003', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000005', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000004', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000006', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000005', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000007', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000006', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000008', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000007', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000009', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000008', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000010', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000009', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000011', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000000a', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000012', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000000b', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000013', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000000c', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000014', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000000d', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000015', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000000e', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000016', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000000f', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000017', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000010', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000018', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000011', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000019', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000012', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000020', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000013', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000021', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000014', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000022', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000015', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000023', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000016', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000024', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000017', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000025', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000018', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000026', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000019', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000027', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000001a', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000028', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000001b', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000029', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000001c', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000030', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000001d', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000031', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000001e', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000032', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000001f', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000033', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000020', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000034', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000021', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000035', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000022', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000036', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000023', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000037', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000024', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000038', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000025', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000039', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000026', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000040', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000027', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000041', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000028', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000042', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000029', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000043', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000002a', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000044', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000002b', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000045', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000002c', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000046', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000002d', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000047', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000002e', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000048', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000002f', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000049', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000030', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000050', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000031', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000051', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000032', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000052', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000033', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000053', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000034', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000054', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000035', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000055', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000036', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000056', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000037', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000057', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000038', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000058', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000039', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000059', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000003a', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000060', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000003b', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000061', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000003c', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000062', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000003d', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000063', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000003e', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000064', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000003f', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000065', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000040', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000066', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000041', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000067', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000042', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000068', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000043', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000069', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000044', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000070', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000045', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000071', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000046', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000072', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000047', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000073', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000048', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000074', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-000000000049', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000075', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000004a', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000076', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000004b', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000077', '01900000-0000-7000-8000-000000000002', '01900010-0000-7000-8000-00000000004c', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000078', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000000', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000079', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000001', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000080', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000002', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000081', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000003', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000082', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000004', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000083', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000005', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000084', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000006', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000085', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000007', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000086', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000008', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000087', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000009', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000088', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000000a', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000089', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000000b', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000090', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000000c', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000091', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000000d', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000092', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000000e', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000093', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000000f', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000094', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000045', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000095', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000046', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000096', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000047', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000097', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000048', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000098', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000010', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000099', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000049', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000100', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000004a', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000101', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000004b', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000102', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000004c', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000103', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000011', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000104', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000012', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000105', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000013', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000106', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000021', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000107', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000022', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000108', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000023', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000109', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000024', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000110', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000014', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000111', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000025', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000112', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000026', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000113', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000027', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000114', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000028', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000115', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000015', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000116', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000029', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000117', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000002a', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000118', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000002b', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000119', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000002c', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000120', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000016', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000121', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000002d', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000122', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000002e', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000123', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000002f', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000124', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000030', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000125', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000017', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000126', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000018', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000127', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000031', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000128', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000032', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000129', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000033', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000130', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000034', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000131', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000019', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000132', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000035', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000133', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000036', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000134', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000037', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000135', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000038', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000136', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000001a', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000137', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000001b', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000138', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000039', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000139', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000003a', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000140', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000003b', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000141', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000003c', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000142', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000001c', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000143', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000041', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000144', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000042', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000145', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000043', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000146', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000044', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000147', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000001d', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000148', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000003d', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000149', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000003e', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000150', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000003f', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000151', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000040', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000152', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000001e', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000153', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-00000000001f', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000154', '01900000-0000-7000-8000-000000000003', '01900010-0000-7000-8000-000000000020', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000155', '01900000-0000-7000-8000-000000000001', '01900010-0000-7000-8000-000000000000', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000156', '01900000-0000-7000-8000-000000000001', '01900010-0000-7000-8000-00000000000b', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000157', '01900000-0000-7000-8000-000000000001', '01900010-0000-7000-8000-00000000000c', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000158', '01900000-0000-7000-8000-000000000001', '01900010-0000-7000-8000-00000000000d', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000159', '01900000-0000-7000-8000-000000000001', '01900010-0000-7000-8000-000000000011', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);

-- End RBAC seed
