/**
 * Generates `seed-local-rbac.sql` from `menuSeeds` + role roots (single source of truth in TS).
 * Run: pnpm exec tsx db/seed/local/generate-rbac-seed-sql.ts
 *
 * Idempotent: clears previous seeded menus (`m-*`) and their role links, then re-inserts
 * three fixed roles (user / admin / superadmin), all menus, and `sys_menu_role`.
 * Does not create auth users — assign roles in the admin UI or via sign-up defaults.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";

import { menuSeeds, type MenuSeed } from "../menus";
import { ADMIN_MENU_ROOT_KEYS, USER_MENU_ROOT_KEYS } from "../menus/role-menu-roots";
import { LOCAL_ROLE_IDS } from "./role-ids";

const OUT = path.join(import.meta.dirname, "seed-local-rbac.sql");

function sortMenusForInsert(seeds: MenuSeed[]): MenuSeed[] {
  const out: MenuSeed[] = [];
  const remaining = [...seeds];
  while (remaining.length) {
    const idx = remaining.findIndex((s) => !s.parentKey || out.some((o) => o.key === s.parentKey));
    if (idx === -1) throw new Error("[generate-rbac-seed-sql] Invalid menu seeds");
    out.push(remaining[idx]!);
    remaining.splice(idx, 1);
  }
  return out;
}

function menuPk(key: string) {
  return `m-${key}`;
}

function collectKeysFromRoots(roots: Set<string>, seeds: MenuSeed[]): Set<string> {
  const result = new Set<string>();
  const walk = (key: string) => {
    if (result.has(key)) return;
    result.add(key);
    for (const s of seeds) {
      if (s.parentKey === key) walk(s.key);
    }
  };
  for (const r of roots) walk(r);
  return result;
}

function sqlStr(s: string | null | undefined): string {
  if (s == null) return "NULL";
  return `'${String(s).replace(/'/g, "''")}'`;
}

function sqlInt(n: number | null | undefined): string {
  if (n == null) return "NULL";
  return String(n);
}

const TS = `(CAST(unixepoch('subsecond') * 1000 AS INTEGER))`;

function main() {
  const ordered = sortMenusForInsert(menuSeeds);
  const orderedReverse = [...ordered].reverse();
  const allKeys = new Set(menuSeeds.map((s) => s.key));
  const adminKeys = collectKeysFromRoots(ADMIN_MENU_ROOT_KEYS, menuSeeds);
  const userKeys = collectKeysFromRoots(USER_MENU_ROOT_KEYS, menuSeeds);

  const lines: string[] = [
    "-- Generated by db/seed/local/generate-rbac-seed-sql.ts — do not edit by hand.",
    "-- Re-run: pnpm db:generate:seed-sql",
    "--",
    "-- Fixed RBAC: roles user / admin / superadmin + full menu tree + role–menu links.",
    "-- Retry-safe: removes old seeded menu rows (id GLOB 'm-*') and links, then re-inserts.",
    "-- Auth users are not created here — use the app UI (or sign-up) and assign roles there.",
    "",
    "PRAGMA foreign_keys = ON;",
    "",
    "-- Reset: links to seeded menus first (any role), then menus child-before-parent",
    "DELETE FROM sys_menu_role WHERE menu_id GLOB 'm-*';",
    "",
    "-- Remove seeded menu rows (FK: children before parents)",
  ];

  for (const s of orderedReverse) {
    lines.push(`DELETE FROM sys_menu WHERE id = ${sqlStr(menuPk(s.key))};`);
  }
  /** Menus removed from `menuSeeds`; keep so re-seed cleans old local DB rows */
  for (const id of [
    "m-ai-image",
    "m-profile-link-category",
    "m-news-detail",
    "m-news-category",
    "m-blog-category",
    "m-blog-tag",
  ] as const) {
    lines.push(`DELETE FROM sys_menu WHERE id = ${sqlStr(id)};`);
  }

  lines.push(
    "",
    "-- Three application roles (fixed UUIDs; `user` = default sign-up role in rbac-login)",
    `INSERT OR REPLACE INTO sys_role (id, name, value, description, remark, status, created_at, updated_at) VALUES (`,
    `  '${LOCAL_ROLE_IDS.user}', 'User', 'user', 'Default sign-up role', NULL, 1, ${TS}, ${TS}`,
    `);`,
    `INSERT OR REPLACE INTO sys_role (id, name, value, description, remark, status, created_at, updated_at) VALUES (`,
    `  '${LOCAL_ROLE_IDS.superadmin}', 'Super Admin', 'superadmin', 'Full menu access', NULL, 1, ${TS}, ${TS}`,
    `);`,
    `INSERT OR REPLACE INTO sys_role (id, name, value, description, remark, status, created_at, updated_at) VALUES (`,
    `  '${LOCAL_ROLE_IDS.admin}', 'Admin', 'admin', 'Admin menu bundle', NULL, 1, ${TS}, ${TS}`,
    `);`,
    "",
    "-- Menus (parent before child)",
  );

  for (const s of ordered) {
    const id = menuPk(s.key);
    const parentId = s.parentKey ? sqlStr(menuPk(s.parentKey)) : "NULL";
    lines.push(
      `INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (`,
      `  ${sqlStr(id)}, ${sqlStr(s.name)}, ${s.type}, ${sqlStr(s.description)}, ${sqlStr(s.remark)}, ${sqlStr(s.icon)}, ${sqlStr(s.path)}, ${sqlStr(s.pathFile)}, ${sqlInt(s.status ?? 1)}, ${sqlInt(s.isShow ?? 1)}, ${sqlInt(s.isCache ?? 0)}, ${sqlStr(s.permission)}, ${sqlInt(s.isLink ?? 0)}, ${sqlInt(s.orderNo ?? 0)}, ${TS}, ${TS}, ${parentId}`,
      `);`,
    );
  }

  lines.push("", "-- Role–menu links");

  let mrCounter = 1;
  function nextMenuRoleId(): string {
    const n = String(mrCounter++).padStart(12, "0");
    return `01900030-0000-7000-8000-${n}`;
  }

  const pairs: { roleId: string; keys: Set<string> }[] = [
    { roleId: LOCAL_ROLE_IDS.superadmin, keys: allKeys },
    { roleId: LOCAL_ROLE_IDS.admin, keys: adminKeys },
    { roleId: LOCAL_ROLE_IDS.user, keys: userKeys },
  ];

  for (const { roleId, keys } of pairs) {
    for (const key of keys) {
      if (!allKeys.has(key)) continue;
      const id = nextMenuRoleId();
      lines.push(
        `INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (`,
        `  '${id}', '${roleId}', '${menuPk(key)}', ${TS}, ${TS}`,
        `);`,
      );
    }
  }

  lines.push("", "-- End RBAC seed");

  writeFileSync(OUT, lines.join("\n") + "\n", "utf8");
  console.log(
    `[generate-rbac-seed-sql] Wrote ${OUT} (${ordered.length} menus, ${mrCounter - 1} menu_role rows).`,
  );
}

main();
