-- Generated by db/seed/local/generate-rbac-seed-sql.ts — do not edit by hand.
-- Re-run: pnpm db:generate:seed-sql
--
-- Fixed RBAC: roles user / admin / superadmin + full menu tree + role–menu links.
-- Retry-safe: removes old seeded menu rows (id GLOB 'm-*') and links, then re-inserts.
-- Auth users are not created here — use the app UI (or sign-up) and assign roles there.

PRAGMA foreign_keys = ON;

-- Reset: links to seeded menus first (any role), then menus child-before-parent
DELETE FROM sys_menu_role WHERE menu_id GLOB 'm-*';

-- Remove seeded menu rows (FK: children before parents)
DELETE FROM sys_menu WHERE id = 'm-perm-tools-storage-delete';
DELETE FROM sys_menu WHERE id = 'm-perm-tools-storage-update';
DELETE FROM sys_menu WHERE id = 'm-perm-tools-storage-create';
DELETE FROM sys_menu WHERE id = 'm-perm-tools-storage-read';
DELETE FROM sys_menu WHERE id = 'm-perm-tools-mail-delete';
DELETE FROM sys_menu WHERE id = 'm-perm-tools-mail-update';
DELETE FROM sys_menu WHERE id = 'm-perm-tools-mail-create';
DELETE FROM sys_menu WHERE id = 'm-perm-tools-mail-read';
DELETE FROM sys_menu WHERE id = 'm-perm-system-monitor-operate-delete';
DELETE FROM sys_menu WHERE id = 'm-perm-system-monitor-operate-update';
DELETE FROM sys_menu WHERE id = 'm-perm-system-monitor-operate-create';
DELETE FROM sys_menu WHERE id = 'm-perm-system-monitor-operate-read';
DELETE FROM sys_menu WHERE id = 'm-perm-system-monitor-serve-delete';
DELETE FROM sys_menu WHERE id = 'm-perm-system-monitor-serve-update';
DELETE FROM sys_menu WHERE id = 'm-perm-system-monitor-serve-create';
DELETE FROM sys_menu WHERE id = 'm-perm-system-monitor-serve-read';
DELETE FROM sys_menu WHERE id = 'm-perm-system-monitor-loginlog-delete';
DELETE FROM sys_menu WHERE id = 'm-perm-system-monitor-loginlog-update';
DELETE FROM sys_menu WHERE id = 'm-perm-system-monitor-loginlog-create';
DELETE FROM sys_menu WHERE id = 'm-perm-system-monitor-loginlog-read';
DELETE FROM sys_menu WHERE id = 'm-perm-system-config-delete';
DELETE FROM sys_menu WHERE id = 'm-perm-system-config-update';
DELETE FROM sys_menu WHERE id = 'm-perm-system-config-create';
DELETE FROM sys_menu WHERE id = 'm-perm-system-config-read';
DELETE FROM sys_menu WHERE id = 'm-perm-system-dict-delete';
DELETE FROM sys_menu WHERE id = 'm-perm-system-dict-update';
DELETE FROM sys_menu WHERE id = 'm-perm-system-dict-create';
DELETE FROM sys_menu WHERE id = 'm-perm-system-dict-read';
DELETE FROM sys_menu WHERE id = 'm-perm-system-dept-delete';
DELETE FROM sys_menu WHERE id = 'm-perm-system-dept-update';
DELETE FROM sys_menu WHERE id = 'm-perm-system-dept-create';
DELETE FROM sys_menu WHERE id = 'm-perm-system-dept-read';
DELETE FROM sys_menu WHERE id = 'm-perm-system-menu-delete';
DELETE FROM sys_menu WHERE id = 'm-perm-system-menu-update';
DELETE FROM sys_menu WHERE id = 'm-perm-system-menu-create';
DELETE FROM sys_menu WHERE id = 'm-perm-system-menu-read';
DELETE FROM sys_menu WHERE id = 'm-perm-system-role-delete';
DELETE FROM sys_menu WHERE id = 'm-perm-system-role-update';
DELETE FROM sys_menu WHERE id = 'm-perm-system-role-create';
DELETE FROM sys_menu WHERE id = 'm-perm-system-role-read';
DELETE FROM sys_menu WHERE id = 'm-perm-system-user-delete';
DELETE FROM sys_menu WHERE id = 'm-perm-system-user-update';
DELETE FROM sys_menu WHERE id = 'm-perm-system-user-create';
DELETE FROM sys_menu WHERE id = 'm-perm-system-user-read';
DELETE FROM sys_menu WHERE id = 'm-system-monitor-serve';
DELETE FROM sys_menu WHERE id = 'm-system-monitor-operate';
DELETE FROM sys_menu WHERE id = 'm-system-monitor-loginlog';
DELETE FROM sys_menu WHERE id = 'm-system-monitor';
DELETE FROM sys_menu WHERE id = 'm-system-config';
DELETE FROM sys_menu WHERE id = 'm-system-dict-item';
DELETE FROM sys_menu WHERE id = 'm-system-dict';
DELETE FROM sys_menu WHERE id = 'm-system-dept';
DELETE FROM sys_menu WHERE id = 'm-system-menu';
DELETE FROM sys_menu WHERE id = 'm-system-role';
DELETE FROM sys_menu WHERE id = 'm-system-user';
DELETE FROM sys_menu WHERE id = 'm-system';
DELETE FROM sys_menu WHERE id = 'm-about';
DELETE FROM sys_menu WHERE id = 'm-tools-storage';
DELETE FROM sys_menu WHERE id = 'm-tools-mail';
DELETE FROM sys_menu WHERE id = 'm-tools';
DELETE FROM sys_menu WHERE id = 'm-profile-link';
DELETE FROM sys_menu WHERE id = 'm-profile-home';
DELETE FROM sys_menu WHERE id = 'm-profile';
DELETE FROM sys_menu WHERE id = 'm-blog-detail';
DELETE FROM sys_menu WHERE id = 'm-blog-edit-article';
DELETE FROM sys_menu WHERE id = 'm-blog-edit';
DELETE FROM sys_menu WHERE id = 'm-blog-list';
DELETE FROM sys_menu WHERE id = 'm-blog';
DELETE FROM sys_menu WHERE id = 'm-news-edit';
DELETE FROM sys_menu WHERE id = 'm-news-list';
DELETE FROM sys_menu WHERE id = 'm-news';
DELETE FROM sys_menu WHERE id = 'm-ai-chatbot';
DELETE FROM sys_menu WHERE id = 'm-ai';
DELETE FROM sys_menu WHERE id = 'm-dashboard';
DELETE FROM sys_menu WHERE id = 'm-ai-image';
DELETE FROM sys_menu WHERE id = 'm-profile-link-category';
DELETE FROM sys_menu WHERE id = 'm-news-detail';
DELETE FROM sys_menu WHERE id = 'm-news-category';
DELETE FROM sys_menu WHERE id = 'm-blog-category';
DELETE FROM sys_menu WHERE id = 'm-blog-tag';

-- Three application roles (fixed UUIDs; `user` = default sign-up role in rbac-login)
INSERT OR REPLACE INTO sys_role (id, name, value, description, remark, status, created_at, updated_at) VALUES (
  '01900000-0000-7000-8000-000000000001', 'User', 'user', 'Default sign-up role', NULL, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT OR REPLACE INTO sys_role (id, name, value, description, remark, status, created_at, updated_at) VALUES (
  '01900000-0000-7000-8000-000000000002', 'Super Admin', 'superadmin', 'Full menu access', NULL, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT OR REPLACE INTO sys_role (id, name, value, description, remark, status, created_at, updated_at) VALUES (
  '01900000-0000-7000-8000-000000000003', 'Admin', 'admin', 'Admin menu bundle', NULL, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);

-- Menus (parent before child)
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-dashboard', 'Dashboard', 2, NULL, NULL, 'DashboardOutlined', '/dashboard', 'admin/dashboard', 1, 1, 0, 'dashboard:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), NULL
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-ai', 'AI', 1, NULL, NULL, 'RobotOutlined', '/ai', NULL, 1, 1, 0, NULL, 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), NULL
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-ai-chatbot', 'Chatbot', 2, NULL, NULL, 'MessageOutlined', '/ai/chatbot', 'admin/ai/chatbot', 1, 1, 0, 'system:ai:chatbot:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-ai'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-news', 'News', 1, NULL, NULL, 'NotificationOutlined', '/news', NULL, 1, 1, 0, NULL, 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), NULL
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-news-list', 'List', 2, NULL, NULL, 'UnorderedListOutlined', '/news/list', 'admin/news/list', 1, 1, 0, 'news:list:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-news'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-news-edit', 'Edit', 2, NULL, NULL, 'FormOutlined', '/news/edit', 'admin/news/edit', 1, 1, 0, 'news:list:read', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-news'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-blog', '博客', 1, NULL, NULL, 'EditOutlined', '/blog', NULL, 1, 1, 0, NULL, 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), NULL
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-blog-list', '列表', 2, NULL, NULL, 'UnorderedListOutlined', '/blog/list', 'admin/blog/list', 1, 1, 0, 'blog:list:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-blog'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-blog-edit', '新建文章', 2, NULL, NULL, 'FormOutlined', '/blog/edit', 'admin/blog/create', 1, 1, 0, 'blog:list:read', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-blog'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-blog-edit-article', '编辑', 2, NULL, NULL, 'EditOutlined', '/blog/edit/:id', 'admin/blog/edit', 1, 0, 0, 'blog:list:read', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-blog'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-blog-detail', 'Detail', 2, NULL, NULL, 'FileTextOutlined', '/blog/detail', 'admin/blog/detail', 1, 0, 0, 'blog:detail:read', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-blog'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-profile', 'Profile', 1, NULL, NULL, 'UserOutlined', '/profile', NULL, 1, 1, 0, NULL, 0, 5, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), NULL
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-profile-home', 'Account', 2, NULL, NULL, 'HomeOutlined', '/profile/account', 'admin/profile/account', 1, 1, 0, 'profile:account:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-profile'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-profile-link', 'Link', 2, NULL, NULL, 'LinkOutlined', '/profile/link', 'admin/profile/link/category', 1, 1, 0, 'profile:link:read', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-profile'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-tools', 'Tools', 1, NULL, NULL, 'ToolOutlined', '/tools', NULL, 1, 1, 0, NULL, 0, 6, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), NULL
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-tools-mail', 'Mail', 2, NULL, NULL, 'MailOutlined', '/tools/mail', 'admin/tools/mail', 1, 1, 0, 'tools:mail:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-tools'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-tools-storage', 'Storage', 2, NULL, NULL, 'DatabaseOutlined', '/tools/storage', 'admin/tools/storage', 1, 1, 0, 'tools:storage:read', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-tools'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-about', 'About', 2, NULL, NULL, 'InfoCircleOutlined', '/about', 'admin/about', 1, 1, 0, 'about:read', 0, 8, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), NULL
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-system', 'System', 1, NULL, NULL, 'SettingOutlined', '/system', NULL, 1, 1, 0, NULL, 0, 7, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), NULL
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-system-user', 'User', 2, NULL, NULL, 'TeamOutlined', '/system/user', 'admin/system/user', 1, 1, 0, 'system:user:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-system-role', 'Role', 2, NULL, NULL, 'UserSwitchOutlined', '/system/role', 'admin/system/role', 1, 1, 0, 'system:role:read', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-system-menu', 'Menu', 2, NULL, NULL, 'MenuOutlined', '/system/menu', 'admin/system/menu', 1, 1, 0, 'system:menu:read', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-system-dept', 'Department', 2, NULL, NULL, 'ApartmentOutlined', '/system/dept', 'admin/system/dept', 1, 1, 0, 'system:dept:read', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-system-dict', 'Dictionary', 2, NULL, NULL, 'BookOutlined', '/system/dict', 'admin/system/dict', 1, 1, 0, 'system:dict:read', 0, 5, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-system-dict-item', 'Dict Item', 2, NULL, NULL, NULL, '/system/dict-item/:id', 'admin/system/dict-item', 1, 0, 0, 'system:dict:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-dict'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-system-config', 'Config', 2, NULL, NULL, 'ControlOutlined', '/system/config', 'admin/system/config', 1, 1, 0, 'system:config:read', 0, 6, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-system-monitor', 'Monitor', 1, NULL, NULL, 'MonitorOutlined', '/system/monitor', NULL, 1, 1, 0, NULL, 0, 7, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-system-monitor-loginlog', 'Login Log', 2, NULL, NULL, 'LoginOutlined', '/system/monitor/loginlog', 'admin/system/monitor/loginlog', 1, 1, 0, 'system:monitor:loginlog:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-monitor'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-system-monitor-operate', 'Operate', 2, NULL, NULL, 'ToolOutlined', '/system/monitor/operate', 'admin/system/monitor/operate', 1, 1, 0, 'system:monitor:operate:read', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-monitor'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-system-monitor-serve', 'Serve', 2, NULL, NULL, 'CloudServerOutlined', '/system/monitor/serve', 'admin/system/monitor/serve', 1, 1, 0, 'system:monitor:serve:read', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-monitor'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-user-read', 'Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:user:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-user'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-user-create', 'Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:user:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-user'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-user-update', 'Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:user:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-user'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-user-delete', 'Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:user:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-user'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-role-read', 'Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:role:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-role'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-role-create', 'Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:role:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-role'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-role-update', 'Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:role:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-role'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-role-delete', 'Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:role:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-role'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-menu-read', 'Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:menu:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-menu'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-menu-create', 'Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:menu:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-menu'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-menu-update', 'Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:menu:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-menu'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-menu-delete', 'Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:menu:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-menu'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-dept-read', 'Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:dept:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-dept'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-dept-create', 'Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:dept:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-dept'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-dept-update', 'Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:dept:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-dept'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-dept-delete', 'Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:dept:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-dept'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-dict-read', 'Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:dict:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-dict'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-dict-create', 'Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:dict:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-dict'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-dict-update', 'Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:dict:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-dict'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-dict-delete', 'Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:dict:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-dict'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-config-read', 'Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:config:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-config'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-config-create', 'Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:config:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-config'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-config-update', 'Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:config:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-config'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-config-delete', 'Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:config:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-config'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-monitor-loginlog-read', 'Login Log Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:loginlog:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-monitor-loginlog'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-monitor-loginlog-create', 'Login Log Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:loginlog:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-monitor-loginlog'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-monitor-loginlog-update', 'Login Log Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:loginlog:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-monitor-loginlog'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-monitor-loginlog-delete', 'Login Log Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:loginlog:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-monitor-loginlog'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-monitor-serve-read', 'Serve Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:serve:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-monitor-serve'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-monitor-serve-create', 'Serve Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:serve:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-monitor-serve'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-monitor-serve-update', 'Serve Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:serve:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-monitor-serve'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-monitor-serve-delete', 'Serve Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:serve:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-monitor-serve'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-monitor-operate-read', 'Operate Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:operate:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-monitor-operate'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-monitor-operate-create', 'Operate Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:operate:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-monitor-operate'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-monitor-operate-update', 'Operate Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:operate:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-monitor-operate'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-system-monitor-operate-delete', 'Operate Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'system:monitor:operate:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-system-monitor-operate'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-tools-mail-read', 'Mail Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'tools:mail:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-tools-mail'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-tools-mail-create', 'Mail Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'tools:mail:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-tools-mail'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-tools-mail-update', 'Mail Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'tools:mail:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-tools-mail'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-tools-mail-delete', 'Mail Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'tools:mail:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-tools-mail'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-tools-storage-read', 'Storage Read', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'tools:storage:read', 0, 1, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-tools-storage'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-tools-storage-create', 'Storage Create', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'tools:storage:create', 0, 2, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-tools-storage'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-tools-storage-update', 'Storage Update', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'tools:storage:update', 0, 3, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-tools-storage'
);
INSERT OR REPLACE INTO sys_menu (id, name, type, description, remark, icon, path, path_file, status, "isShow", "isCache", permission, "isLink", order_no, created_at, updated_at, parent_menu_id) VALUES (
  'm-perm-tools-storage-delete', 'Storage Delete', 3, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'tools:storage:delete', 0, 4, (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), 'm-tools-storage'
);

-- Role–menu links
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000001', '01900000-0000-7000-8000-000000000002', 'm-dashboard', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000002', '01900000-0000-7000-8000-000000000002', 'm-ai', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000003', '01900000-0000-7000-8000-000000000002', 'm-ai-chatbot', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000004', '01900000-0000-7000-8000-000000000002', 'm-news', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000005', '01900000-0000-7000-8000-000000000002', 'm-news-list', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000006', '01900000-0000-7000-8000-000000000002', 'm-news-edit', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000007', '01900000-0000-7000-8000-000000000002', 'm-blog', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000008', '01900000-0000-7000-8000-000000000002', 'm-blog-list', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000009', '01900000-0000-7000-8000-000000000002', 'm-blog-edit', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000010', '01900000-0000-7000-8000-000000000002', 'm-blog-edit-article', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000011', '01900000-0000-7000-8000-000000000002', 'm-blog-detail', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000012', '01900000-0000-7000-8000-000000000002', 'm-profile', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000013', '01900000-0000-7000-8000-000000000002', 'm-profile-home', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000014', '01900000-0000-7000-8000-000000000002', 'm-profile-link', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000015', '01900000-0000-7000-8000-000000000002', 'm-tools', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000016', '01900000-0000-7000-8000-000000000002', 'm-tools-mail', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000017', '01900000-0000-7000-8000-000000000002', 'm-tools-storage', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000018', '01900000-0000-7000-8000-000000000002', 'm-about', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000019', '01900000-0000-7000-8000-000000000002', 'm-system', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000020', '01900000-0000-7000-8000-000000000002', 'm-system-user', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000021', '01900000-0000-7000-8000-000000000002', 'm-system-role', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000022', '01900000-0000-7000-8000-000000000002', 'm-system-menu', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000023', '01900000-0000-7000-8000-000000000002', 'm-system-dept', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000024', '01900000-0000-7000-8000-000000000002', 'm-system-dict', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000025', '01900000-0000-7000-8000-000000000002', 'm-system-dict-item', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000026', '01900000-0000-7000-8000-000000000002', 'm-system-config', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000027', '01900000-0000-7000-8000-000000000002', 'm-system-monitor', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000028', '01900000-0000-7000-8000-000000000002', 'm-system-monitor-loginlog', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000029', '01900000-0000-7000-8000-000000000002', 'm-system-monitor-operate', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000030', '01900000-0000-7000-8000-000000000002', 'm-system-monitor-serve', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000031', '01900000-0000-7000-8000-000000000002', 'm-perm-system-user-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000032', '01900000-0000-7000-8000-000000000002', 'm-perm-system-user-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000033', '01900000-0000-7000-8000-000000000002', 'm-perm-system-user-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000034', '01900000-0000-7000-8000-000000000002', 'm-perm-system-user-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000035', '01900000-0000-7000-8000-000000000002', 'm-perm-system-role-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000036', '01900000-0000-7000-8000-000000000002', 'm-perm-system-role-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000037', '01900000-0000-7000-8000-000000000002', 'm-perm-system-role-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000038', '01900000-0000-7000-8000-000000000002', 'm-perm-system-role-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000039', '01900000-0000-7000-8000-000000000002', 'm-perm-system-menu-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000040', '01900000-0000-7000-8000-000000000002', 'm-perm-system-menu-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000041', '01900000-0000-7000-8000-000000000002', 'm-perm-system-menu-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000042', '01900000-0000-7000-8000-000000000002', 'm-perm-system-menu-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000043', '01900000-0000-7000-8000-000000000002', 'm-perm-system-dept-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000044', '01900000-0000-7000-8000-000000000002', 'm-perm-system-dept-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000045', '01900000-0000-7000-8000-000000000002', 'm-perm-system-dept-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000046', '01900000-0000-7000-8000-000000000002', 'm-perm-system-dept-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000047', '01900000-0000-7000-8000-000000000002', 'm-perm-system-dict-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000048', '01900000-0000-7000-8000-000000000002', 'm-perm-system-dict-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000049', '01900000-0000-7000-8000-000000000002', 'm-perm-system-dict-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000050', '01900000-0000-7000-8000-000000000002', 'm-perm-system-dict-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000051', '01900000-0000-7000-8000-000000000002', 'm-perm-system-config-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000052', '01900000-0000-7000-8000-000000000002', 'm-perm-system-config-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000053', '01900000-0000-7000-8000-000000000002', 'm-perm-system-config-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000054', '01900000-0000-7000-8000-000000000002', 'm-perm-system-config-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000055', '01900000-0000-7000-8000-000000000002', 'm-perm-system-monitor-loginlog-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000056', '01900000-0000-7000-8000-000000000002', 'm-perm-system-monitor-loginlog-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000057', '01900000-0000-7000-8000-000000000002', 'm-perm-system-monitor-loginlog-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000058', '01900000-0000-7000-8000-000000000002', 'm-perm-system-monitor-loginlog-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000059', '01900000-0000-7000-8000-000000000002', 'm-perm-system-monitor-serve-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000060', '01900000-0000-7000-8000-000000000002', 'm-perm-system-monitor-serve-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000061', '01900000-0000-7000-8000-000000000002', 'm-perm-system-monitor-serve-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000062', '01900000-0000-7000-8000-000000000002', 'm-perm-system-monitor-serve-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000063', '01900000-0000-7000-8000-000000000002', 'm-perm-system-monitor-operate-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000064', '01900000-0000-7000-8000-000000000002', 'm-perm-system-monitor-operate-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000065', '01900000-0000-7000-8000-000000000002', 'm-perm-system-monitor-operate-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000066', '01900000-0000-7000-8000-000000000002', 'm-perm-system-monitor-operate-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000067', '01900000-0000-7000-8000-000000000002', 'm-perm-tools-mail-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000068', '01900000-0000-7000-8000-000000000002', 'm-perm-tools-mail-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000069', '01900000-0000-7000-8000-000000000002', 'm-perm-tools-mail-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000070', '01900000-0000-7000-8000-000000000002', 'm-perm-tools-mail-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000071', '01900000-0000-7000-8000-000000000002', 'm-perm-tools-storage-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000072', '01900000-0000-7000-8000-000000000002', 'm-perm-tools-storage-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000073', '01900000-0000-7000-8000-000000000002', 'm-perm-tools-storage-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000074', '01900000-0000-7000-8000-000000000002', 'm-perm-tools-storage-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000075', '01900000-0000-7000-8000-000000000003', 'm-dashboard', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000076', '01900000-0000-7000-8000-000000000003', 'm-ai', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000077', '01900000-0000-7000-8000-000000000003', 'm-ai-chatbot', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000078', '01900000-0000-7000-8000-000000000003', 'm-news', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000079', '01900000-0000-7000-8000-000000000003', 'm-news-list', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000080', '01900000-0000-7000-8000-000000000003', 'm-news-edit', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000081', '01900000-0000-7000-8000-000000000003', 'm-blog', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000082', '01900000-0000-7000-8000-000000000003', 'm-blog-list', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000083', '01900000-0000-7000-8000-000000000003', 'm-blog-edit', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000084', '01900000-0000-7000-8000-000000000003', 'm-blog-edit-article', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000085', '01900000-0000-7000-8000-000000000003', 'm-blog-detail', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000086', '01900000-0000-7000-8000-000000000003', 'm-profile', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000087', '01900000-0000-7000-8000-000000000003', 'm-profile-home', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000088', '01900000-0000-7000-8000-000000000003', 'm-profile-link', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000089', '01900000-0000-7000-8000-000000000003', 'm-tools', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000090', '01900000-0000-7000-8000-000000000003', 'm-tools-mail', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000091', '01900000-0000-7000-8000-000000000003', 'm-perm-tools-mail-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000092', '01900000-0000-7000-8000-000000000003', 'm-perm-tools-mail-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000093', '01900000-0000-7000-8000-000000000003', 'm-perm-tools-mail-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000094', '01900000-0000-7000-8000-000000000003', 'm-perm-tools-mail-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000095', '01900000-0000-7000-8000-000000000003', 'm-tools-storage', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000096', '01900000-0000-7000-8000-000000000003', 'm-perm-tools-storage-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000097', '01900000-0000-7000-8000-000000000003', 'm-perm-tools-storage-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000098', '01900000-0000-7000-8000-000000000003', 'm-perm-tools-storage-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000099', '01900000-0000-7000-8000-000000000003', 'm-perm-tools-storage-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000100', '01900000-0000-7000-8000-000000000003', 'm-about', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000101', '01900000-0000-7000-8000-000000000003', 'm-system', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000102', '01900000-0000-7000-8000-000000000003', 'm-system-user', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000103', '01900000-0000-7000-8000-000000000003', 'm-perm-system-user-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000104', '01900000-0000-7000-8000-000000000003', 'm-perm-system-user-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000105', '01900000-0000-7000-8000-000000000003', 'm-perm-system-user-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000106', '01900000-0000-7000-8000-000000000003', 'm-perm-system-user-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000107', '01900000-0000-7000-8000-000000000003', 'm-system-role', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000108', '01900000-0000-7000-8000-000000000003', 'm-perm-system-role-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000109', '01900000-0000-7000-8000-000000000003', 'm-perm-system-role-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000110', '01900000-0000-7000-8000-000000000003', 'm-perm-system-role-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000111', '01900000-0000-7000-8000-000000000003', 'm-perm-system-role-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000112', '01900000-0000-7000-8000-000000000003', 'm-system-menu', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000113', '01900000-0000-7000-8000-000000000003', 'm-perm-system-menu-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000114', '01900000-0000-7000-8000-000000000003', 'm-perm-system-menu-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000115', '01900000-0000-7000-8000-000000000003', 'm-perm-system-menu-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000116', '01900000-0000-7000-8000-000000000003', 'm-perm-system-menu-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000117', '01900000-0000-7000-8000-000000000003', 'm-system-dept', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000118', '01900000-0000-7000-8000-000000000003', 'm-perm-system-dept-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000119', '01900000-0000-7000-8000-000000000003', 'm-perm-system-dept-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000120', '01900000-0000-7000-8000-000000000003', 'm-perm-system-dept-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000121', '01900000-0000-7000-8000-000000000003', 'm-perm-system-dept-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000122', '01900000-0000-7000-8000-000000000003', 'm-system-dict', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000123', '01900000-0000-7000-8000-000000000003', 'm-system-dict-item', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000124', '01900000-0000-7000-8000-000000000003', 'm-perm-system-dict-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000125', '01900000-0000-7000-8000-000000000003', 'm-perm-system-dict-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000126', '01900000-0000-7000-8000-000000000003', 'm-perm-system-dict-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000127', '01900000-0000-7000-8000-000000000003', 'm-perm-system-dict-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000128', '01900000-0000-7000-8000-000000000003', 'm-system-config', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000129', '01900000-0000-7000-8000-000000000003', 'm-perm-system-config-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000130', '01900000-0000-7000-8000-000000000003', 'm-perm-system-config-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000131', '01900000-0000-7000-8000-000000000003', 'm-perm-system-config-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000132', '01900000-0000-7000-8000-000000000003', 'm-perm-system-config-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000133', '01900000-0000-7000-8000-000000000003', 'm-system-monitor', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000134', '01900000-0000-7000-8000-000000000003', 'm-system-monitor-loginlog', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000135', '01900000-0000-7000-8000-000000000003', 'm-perm-system-monitor-loginlog-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000136', '01900000-0000-7000-8000-000000000003', 'm-perm-system-monitor-loginlog-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000137', '01900000-0000-7000-8000-000000000003', 'm-perm-system-monitor-loginlog-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000138', '01900000-0000-7000-8000-000000000003', 'm-perm-system-monitor-loginlog-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000139', '01900000-0000-7000-8000-000000000003', 'm-system-monitor-operate', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000140', '01900000-0000-7000-8000-000000000003', 'm-perm-system-monitor-operate-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000141', '01900000-0000-7000-8000-000000000003', 'm-perm-system-monitor-operate-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000142', '01900000-0000-7000-8000-000000000003', 'm-perm-system-monitor-operate-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000143', '01900000-0000-7000-8000-000000000003', 'm-perm-system-monitor-operate-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000144', '01900000-0000-7000-8000-000000000003', 'm-system-monitor-serve', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000145', '01900000-0000-7000-8000-000000000003', 'm-perm-system-monitor-serve-read', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000146', '01900000-0000-7000-8000-000000000003', 'm-perm-system-monitor-serve-create', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000147', '01900000-0000-7000-8000-000000000003', 'm-perm-system-monitor-serve-update', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000148', '01900000-0000-7000-8000-000000000003', 'm-perm-system-monitor-serve-delete', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000149', '01900000-0000-7000-8000-000000000001', 'm-dashboard', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000150', '01900000-0000-7000-8000-000000000001', 'm-profile', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000151', '01900000-0000-7000-8000-000000000001', 'm-profile-home', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000152', '01900000-0000-7000-8000-000000000001', 'm-profile-link', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);
INSERT INTO sys_menu_role (id, role_id, menu_id, created_at, updated_at) VALUES (
  '01900030-0000-7000-8000-000000000153', '01900000-0000-7000-8000-000000000001', 'm-about', (CAST(unixepoch('subsecond') * 1000 AS INTEGER)), (CAST(unixepoch('subsecond') * 1000 AS INTEGER))
);

-- End RBAC seed
