export type MenuSeed = {
  key: string;
  parentKey?: string | null;
  name: string;
  type: number;
  path?: string | null;
  pathFile?: string | null;
  permission?: string | null;
  icon?: string | null;
  status?: number;
  isShow?: number;
  isCache?: number;
  isLink?: number;
  orderNo?: number;
  description?: string | null;
  remark?: string | null;
};

/**
 * `name` is an i18n key consumed by `resolveMenuLabel` on the admin client
 * (see `apps/admin/app/utils/client/menu-label.ts`). Keys follow the `menu_*`
 * short namespace declared in `apps/admin/messages/{en,zh}.json`. Type-3
 * permission nodes intentionally keep their plain-English verb so they can
 * be referenced directly from permission strings without going through i18n.
 */
export const menuSeeds: MenuSeed[] = [
  {
    key: "dashboard",
    name: "menu_dashboard",
    type: 2,
    path: "/dashboard",
    pathFile: "admin/dashboard",
    permission: "dashboard:read",
    icon: "DashboardOutlined",
    orderNo: 1,
    isShow: 1,
  },
  {
    key: "ai",
    name: "menu_ai",
    type: 1,
    path: "/ai",
    icon: "RobotOutlined",
    orderNo: 2,
    isShow: 1,
  },
  {
    key: "ai-chatbot",
    parentKey: "ai",
    name: "menu_chatbot",
    type: 2,
    path: "/ai/chatbot",
    pathFile: "admin/ai/chatbot",
    permission: "system:ai:chatbot:read",
    icon: "MessageOutlined",
    orderNo: 1,
    isShow: 1,
  },
  {
    key: "news",
    name: "menu_news",
    type: 1,
    path: "/news",
    icon: "NotificationOutlined",
    orderNo: 3,
    isShow: 1,
  },
  {
    key: "news-list",
    parentKey: "news",
    name: "menu_news_list",
    type: 2,
    path: "/news/list",
    pathFile: "admin/news/list",
    permission: "news:list:read",
    icon: "UnorderedListOutlined",
    orderNo: 1,
    isShow: 1,
  },
  {
    key: "news-edit",
    parentKey: "news",
    name: "menu_news_edit",
    type: 2,
    path: "/news/edit",
    pathFile: "admin/news/edit",
    /** Same gate as list/create API (`news:list:read`). */
    permission: "news:list:read",
    icon: "FormOutlined",
    orderNo: 2,
    isShow: 1,
  },
  {
    key: "blog",
    name: "menu_blog",
    type: 1,
    path: "/blog",
    icon: "EditOutlined",
    orderNo: 4,
    isShow: 1,
  },
  {
    key: "blog-list",
    parentKey: "blog",
    name: "menu_blog_list",
    type: 2,
    path: "/blog/list",
    pathFile: "admin/blog/list",
    permission: "blog:list:read",
    icon: "UnorderedListOutlined",
    orderNo: 1,
    isShow: 1,
  },
  {
    key: "blog-edit",
    parentKey: "blog",
    name: "menu_blog_edit",
    type: 2,
    path: "/blog/edit",
    /** 与路由 `routes/admin/blog/create.tsx`（URL `/blog/edit`）一致，便于侧栏与权限对齐 */
    pathFile: "admin/blog/create",
    /** Same gate as list/create API (`blog:list:read`). */
    permission: "blog:list:read",
    icon: "FormOutlined",
    orderNo: 2,
    isShow: 1,
  },
  {
    key: "blog-edit-article",
    parentKey: "blog",
    name: "menu_blog_edit_article",
    type: 2,
    path: "/blog/edit/:id",
    pathFile: "admin/blog/edit",
    permission: "blog:list:read",
    icon: "EditOutlined",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "blog-detail",
    parentKey: "blog",
    name: "menu_blog_detail",
    type: 2,
    path: "/blog/detail",
    pathFile: "admin/blog/detail",
    permission: "blog:detail:read",
    icon: "FileTextOutlined",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "profile",
    name: "menu_profile",
    type: 1,
    path: "/profile",
    icon: "UserOutlined",
    orderNo: 5,
    isShow: 1,
  },
  {
    key: "profile-home",
    parentKey: "profile",
    name: "menu_account",
    type: 2,
    path: "/profile/account",
    pathFile: "admin/profile/account",
    permission: "profile:account:read",
    icon: "HomeOutlined",
    orderNo: 1,
    isShow: 1,
  },
  {
    key: "profile-link",
    parentKey: "profile",
    name: "menu_link",
    type: 2,
    path: "/profile/link",
    pathFile: "admin/profile/link/category",
    permission: "profile:link:read",
    icon: "LinkOutlined",
    orderNo: 2,
    isShow: 1,
  },
  {
    key: "tools",
    name: "menu_tools",
    type: 1,
    path: "/tools",
    icon: "ToolOutlined",
    orderNo: 6,
    isShow: 1,
  },
  {
    key: "tools-mail",
    parentKey: "tools",
    name: "menu_mail",
    type: 2,
    path: "/tools/mail",
    pathFile: "admin/tools/mail",
    permission: "tools:mail:read",
    icon: "MailOutlined",
    orderNo: 1,
    isShow: 1,
  },
  {
    key: "tools-storage",
    parentKey: "tools",
    name: "menu_storage",
    type: 2,
    path: "/tools/storage",
    pathFile: "admin/tools/storage",
    permission: "tools:storage:read",
    icon: "DatabaseOutlined",
    orderNo: 2,
    isShow: 1,
  },
  {
    key: "about",
    name: "menu_about",
    type: 2,
    path: "/about",
    pathFile: "admin/about",
    permission: "about:read",
    icon: "InfoCircleOutlined",
    orderNo: 9,
    isShow: 1,
  },
  {
    key: "system",
    name: "menu_system",
    type: 1,
    path: "/system",
    icon: "SettingOutlined",
    orderNo: 7,
    isShow: 1,
  },
  {
    key: "system-user",
    parentKey: "system",
    name: "menu_user",
    type: 2,
    path: "/system/user",
    pathFile: "admin/system/user",
    permission: "system:user:read",
    icon: "TeamOutlined",
    orderNo: 1,
    isShow: 1,
  },
  {
    key: "system-role",
    parentKey: "system",
    name: "menu_role",
    type: 2,
    path: "/system/role",
    pathFile: "admin/system/role",
    permission: "system:role:read",
    icon: "UserSwitchOutlined",
    orderNo: 2,
    isShow: 1,
  },
  {
    key: "system-menu",
    parentKey: "system",
    name: "menu_menu",
    type: 2,
    path: "/system/menu",
    pathFile: "admin/system/menu",
    permission: "system:menu:read",
    icon: "MenuOutlined",
    orderNo: 3,
    isShow: 1,
  },
  {
    key: "system-dept",
    parentKey: "system",
    name: "menu_dept",
    type: 2,
    path: "/system/dept",
    pathFile: "admin/system/dept",
    permission: "system:dept:read",
    icon: "ApartmentOutlined",
    orderNo: 4,
    isShow: 1,
  },
  {
    key: "system-dict",
    parentKey: "system",
    name: "menu_dict",
    type: 2,
    path: "/system/dict",
    pathFile: "admin/system/dict",
    permission: "system:dict:read",
    icon: "BookOutlined",
    orderNo: 5,
    isShow: 1,
  },
  {
    key: "system-dict-item",
    parentKey: "system-dict",
    name: "menu_dict_item",
    type: 2,
    path: "/system/dict-item/:id",
    pathFile: "admin/system/dict-item",
    permission: "system:dict:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "system-config",
    parentKey: "system",
    name: "menu_config",
    type: 2,
    path: "/system/config",
    pathFile: "admin/system/config",
    permission: "system:config:read",
    icon: "ControlOutlined",
    orderNo: 6,
    isShow: 1,
  },
  {
    key: "system-monitor",
    parentKey: "system",
    name: "menu_monitor",
    type: 1,
    path: "/system/monitor",
    icon: "MonitorOutlined",
    orderNo: 7,
    isShow: 1,
  },
  {
    key: "system-monitor-loginlog",
    parentKey: "system-monitor",
    name: "menu_login_log",
    type: 2,
    path: "/system/monitor/loginlog",
    pathFile: "admin/system/monitor/loginlog",
    permission: "system:monitor:loginlog:read",
    icon: "LoginOutlined",
    orderNo: 1,
    isShow: 1,
  },
  {
    key: "system-monitor-operate",
    parentKey: "system-monitor",
    name: "menu_operate",
    type: 2,
    path: "/system/monitor/operate",
    pathFile: "admin/system/monitor/operate",
    permission: "system:monitor:operate:read",
    icon: "ToolOutlined",
    orderNo: 2,
    isShow: 1,
  },
  {
    key: "system-monitor-serve",
    parentKey: "system-monitor",
    name: "menu_serve",
    type: 2,
    path: "/system/monitor/serve",
    pathFile: "admin/system/monitor/serve",
    permission: "system:monitor:serve:read",
    icon: "CloudServerOutlined",
    orderNo: 3,
    isShow: 1,
  },
  {
    key: "docs",
    name: "menu_docs",
    type: 1,
    path: "/docs",
    icon: "FileTextOutlined",
    orderNo: 8,
    isShow: 1,
  },
  {
    key: "docs-changelog",
    parentKey: "docs",
    name: "menu_docs_changelog",
    type: 2,
    path: "/docs/changelog",
    pathFile: "admin/docs/changelog",
    permission: "docs:changelog:read",
    icon: "HistoryOutlined",
    orderNo: 1,
    isShow: 1,
  },
  {
    key: "docs-feedback",
    parentKey: "docs",
    name: "menu_docs_feedback",
    type: 2,
    path: "/docs/feedback",
    pathFile: "admin/docs/feedback",
    permission: "docs:feedback:read",
    icon: "MessageOutlined",
    orderNo: 2,
    isShow: 1,
  },
  {
    key: "perm-system-user-read",
    parentKey: "system-user",
    name: "Read",
    type: 3,
    permission: "system:user:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-system-user-create",
    parentKey: "system-user",
    name: "Create",
    type: 3,
    permission: "system:user:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-system-user-update",
    parentKey: "system-user",
    name: "Update",
    type: 3,
    permission: "system:user:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-system-user-delete",
    parentKey: "system-user",
    name: "Delete",
    type: 3,
    permission: "system:user:delete",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "perm-system-role-read",
    parentKey: "system-role",
    name: "Read",
    type: 3,
    permission: "system:role:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-system-role-create",
    parentKey: "system-role",
    name: "Create",
    type: 3,
    permission: "system:role:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-system-role-update",
    parentKey: "system-role",
    name: "Update",
    type: 3,
    permission: "system:role:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-system-role-delete",
    parentKey: "system-role",
    name: "Delete",
    type: 3,
    permission: "system:role:delete",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "perm-system-menu-read",
    parentKey: "system-menu",
    name: "Read",
    type: 3,
    permission: "system:menu:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-system-menu-create",
    parentKey: "system-menu",
    name: "Create",
    type: 3,
    permission: "system:menu:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-system-menu-update",
    parentKey: "system-menu",
    name: "Update",
    type: 3,
    permission: "system:menu:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-system-menu-delete",
    parentKey: "system-menu",
    name: "Delete",
    type: 3,
    permission: "system:menu:delete",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "perm-system-dept-read",
    parentKey: "system-dept",
    name: "Read",
    type: 3,
    permission: "system:dept:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-system-dept-create",
    parentKey: "system-dept",
    name: "Create",
    type: 3,
    permission: "system:dept:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-system-dept-update",
    parentKey: "system-dept",
    name: "Update",
    type: 3,
    permission: "system:dept:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-system-dept-delete",
    parentKey: "system-dept",
    name: "Delete",
    type: 3,
    permission: "system:dept:delete",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "perm-system-dict-read",
    parentKey: "system-dict",
    name: "Read",
    type: 3,
    permission: "system:dict:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-system-dict-create",
    parentKey: "system-dict",
    name: "Create",
    type: 3,
    permission: "system:dict:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-system-dict-update",
    parentKey: "system-dict",
    name: "Update",
    type: 3,
    permission: "system:dict:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-system-dict-delete",
    parentKey: "system-dict",
    name: "Delete",
    type: 3,
    permission: "system:dict:delete",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "perm-system-config-read",
    parentKey: "system-config",
    name: "Read",
    type: 3,
    permission: "system:config:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-system-config-create",
    parentKey: "system-config",
    name: "Create",
    type: 3,
    permission: "system:config:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-system-config-update",
    parentKey: "system-config",
    name: "Update",
    type: 3,
    permission: "system:config:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-system-config-delete",
    parentKey: "system-config",
    name: "Delete",
    type: 3,
    permission: "system:config:delete",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-loginlog-read",
    parentKey: "system-monitor-loginlog",
    name: "Read",
    type: 3,
    permission: "system:monitor:loginlog:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-loginlog-create",
    parentKey: "system-monitor-loginlog",
    name: "Create",
    type: 3,
    permission: "system:monitor:loginlog:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-loginlog-update",
    parentKey: "system-monitor-loginlog",
    name: "Update",
    type: 3,
    permission: "system:monitor:loginlog:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-loginlog-delete",
    parentKey: "system-monitor-loginlog",
    name: "Delete",
    type: 3,
    permission: "system:monitor:loginlog:delete",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-serve-read",
    parentKey: "system-monitor-serve",
    name: "Read",
    type: 3,
    permission: "system:monitor:serve:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-serve-create",
    parentKey: "system-monitor-serve",
    name: "Create",
    type: 3,
    permission: "system:monitor:serve:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-serve-update",
    parentKey: "system-monitor-serve",
    name: "Update",
    type: 3,
    permission: "system:monitor:serve:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-serve-delete",
    parentKey: "system-monitor-serve",
    name: "Delete",
    type: 3,
    permission: "system:monitor:serve:delete",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-operate-read",
    parentKey: "system-monitor-operate",
    name: "Read",
    type: 3,
    permission: "system:monitor:operate:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-operate-create",
    parentKey: "system-monitor-operate",
    name: "Create",
    type: 3,
    permission: "system:monitor:operate:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-operate-update",
    parentKey: "system-monitor-operate",
    name: "Update",
    type: 3,
    permission: "system:monitor:operate:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-system-monitor-operate-delete",
    parentKey: "system-monitor-operate",
    name: "Delete",
    type: 3,
    permission: "system:monitor:operate:delete",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "perm-tools-mail-read",
    parentKey: "tools-mail",
    name: "Read",
    type: 3,
    permission: "tools:mail:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-tools-mail-create",
    parentKey: "tools-mail",
    name: "Create",
    type: 3,
    permission: "tools:mail:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-tools-mail-update",
    parentKey: "tools-mail",
    name: "Update",
    type: 3,
    permission: "tools:mail:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-tools-mail-delete",
    parentKey: "tools-mail",
    name: "Delete",
    type: 3,
    permission: "tools:mail:delete",
    orderNo: 4,
    isShow: 0,
  },
  {
    key: "perm-tools-storage-read",
    parentKey: "tools-storage",
    name: "Read",
    type: 3,
    permission: "tools:storage:read",
    orderNo: 1,
    isShow: 0,
  },
  {
    key: "perm-tools-storage-create",
    parentKey: "tools-storage",
    name: "Create",
    type: 3,
    permission: "tools:storage:create",
    orderNo: 2,
    isShow: 0,
  },
  {
    key: "perm-tools-storage-update",
    parentKey: "tools-storage",
    name: "Update",
    type: 3,
    permission: "tools:storage:update",
    orderNo: 3,
    isShow: 0,
  },
  {
    key: "perm-tools-storage-delete",
    parentKey: "tools-storage",
    name: "Delete",
    type: 3,
    permission: "tools:storage:delete",
    orderNo: 4,
    isShow: 0,
  },
];
